- pkg:cargo/kasa-prometheus@0.1.0
- pkg:cargo/kasa-prometheus@0.2.0
- pkg:cargo/kasa-prometheus@0.3.0
- pkg:cargo/kasa-prometheus@0.4.0
- pkg:cargo/kasa-prometheus@0.4.1
- pkg:cargo/kasa-prometheus@0.5.0
